<?php

namespace App\Admin\Controllers;

use App\Admin\Repositories\Feedback;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Http\Controllers\AdminController;
use Dcat\Admin\Layout\Content;

class FeedbackController extends AdminController
{
    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        return Grid::make(new Feedback(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('subject');
            //            $grid->column('feed_type');
            $grid->column('author');
            $grid->column('email');
            $grid->column('phone');
            $grid->column('content')->display(function ($items) {
                return $items['message'] ?? '';
            });
            $grid->column('created_at')->sortable();

            $grid->filter(function (Grid\Filter $filter) {
                $filter->equal('id');

            });

            $grid->model()->orderByDesc('id');
            $grid->disableCreateButton();
        });
    }

    public function show($id, Content $content)
    {
        return parent::show($id, $content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new Feedback(), function (Form $form) {
            $form->display('id');
            $form->text('subject');
            //            $form->text('feed_type');
            $form->text('author');
            $form->text('email');
            $form->text('phone');
            $form->display('content')->with(function ($items) {
                return "{$items['message']}";
            });
            //            $form->text('ip');
            //            $form->text('useragent');

            $form->display('created_at');
            $form->display('updated_at');
        });
    }
}
