<?php

namespace App\Admin\Controllers;

use App\Admin\Repositories\Page;
use App\Models\Category;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Http\Controllers\AdminController;
use Dcat\Admin\Layout\Content;
use Illuminate\Validation\Rule;

class PageController extends AdminController
{
    public function __construct()
    {
        if (($cate_id = \request('cate_id')) && \request()->method() == 'GET') {
            $this->title = Category::query()->where('id', $cate_id)->get()->pluck('name')->first();
        }
    }

    public function index(Content $content)
    {
        $content->breadcrumb($this->title);

        return parent::index($content); // TODO: Change the autogenerated stub
    }

    public function create(Content $content)
    {
        $content->breadcrumb($this->title, \route('dcat.admin.page.index', \request('cate_id')));
        $content->breadcrumb(__('admin.create'));

        return parent::create($content); // TODO: Change the autogenerated stub
    }

    public function edit($id, Content $content)
    {
        $content->breadcrumb($this->title, \route('dcat.admin.page.index', \request('cate_id')));
        $content->breadcrumb(__('admin.edit'));
        $id = request()->route()->parameter('page');

        return parent::edit($id, $content); // TODO: Change the autogenerated stub
    }

    public function update($id)
    {
        $id = request()->route()->parameter('page');

        return parent::update($id); // TODO: Change the autogenerated stub
    }

    public function destroy($id)
    {
        $id = request()->route()->parameter('page');

        return parent::destroy($id); // TODO: Change the autogenerated stub
    }

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        return Grid::make(new Page(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('title')->editable();
            $grid->column('alias');
            //            $grid->column('cate_id');
            //            $grid->column('cover')->image('',150,150);
            $grid->column('hits');
            //            $grid->column('template');
            $grid->column('lang')->using(['zh' => '中文', 'en' => '英文'])->filter();
            $grid->column('updated_at')->sortable();

            $grid->filter(function (Grid\Filter $filter) {
                $filter->equal('id');
                $filter->like('title');
            })
                ->model()
                ->orderBy('sort')
                ->orderByDesc('id');

            if ($cate_id = \request('cate_id')) {
                $grid->model()->where('cate_id', $cate_id);
            }
        });
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new Page(), function (Form $form) {
            $form->display('id');
            $form->text('title')->required();

            $form->text('alias')->required()
                ->creationRules([Rule::unique('pages')->where('lang', \request('lang'))])
                ->updateRules([Rule::unique('pages')->ignore($form->model()->id)->where('lang', \request('lang'))])
                ->help($form->isEditing() ? '如需修改,请修改对应引用链接的URL' : '');
            $form->hidden('cate_id')->default(\request('cate_id'));
            $form->image('cover')
                ->move('page')
                ->removable()
                ->maxSize(1024 * 3)
                ->uniqueName()
                ->scaleDown(1920)
                ->autoUpload()
                ->help('最大上传3m');
            $form->textarea('description')->rows(2);
            $form->text('keywords')->help(__('global.helper.keyword'));
            $form->editor('content');
            $form->radio('lang')->options(['zh' => '中文', 'en' => '英文'])->default('zh')->required();
            $form->display('created_at');
            $form->display('updated_at');

            if ($form->isEditing()) {
                $form->tools(function (Form\Tools $tools) use ($form) {
                    $tools->append('<div class="btn-group pull-right" style="margin-right: 5px">
    <a href="/'.$form->model()->lang.'/page/'.$form->model()->alias.'" target="_blank" class="btn btn-sm btn-primary "><i class="feather icon-eye"></i><span class="d-none d-sm-inline">&nbsp;预览</span></a>
</div>');
                });
            }
        });
    }
}
