<?php

namespace App\Admin\Controllers;

use App\Admin\Repositories\Gallery;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Http\Controllers\AdminController;
use Dcat\Admin\Layout\Content;

class ProjectController extends AdminController
{
    protected $title = '工程案例';

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        return Grid::make(new Gallery(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('title', '标题')->editable();
            $grid->column('tags', '标签')->label();
            $grid->column('images', '图片')->limit(2, '')->image(null, height: 150);
            $grid->column('lang', '语言');
            $grid->column('created_at');

            $grid->filter(function (Grid\Filter $filter) {
                $filter->equal('id');
            });

            $grid->model()
                ->whereJsonDoesntContain('tags', '相册')
                ->orderBy('id', 'desc');
        });
    }

    public function show($id, Content $content)
    {
        return parent::show($id, $content); // TODO: Change the autogenerated stub
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new Gallery(), function (Form $form) {
            $form->display('id');
            $form->text('title');
            $form->tags('tags');
            $form->multipleImage('images')
                ->sortable()
                ->maxSize(1024 * 3)
                ->uniqueName()
                ->autoUpload()
                ->scaleDown(1024, 960)
                ->thumbnail('s', 300, 300)
                ->toWebp(90);
            $form->editor('description');
            $form->radio('lang')->options(['zh' => '中文', 'en' => 'English'])->default('zh');

            $form->display('created_at');
            $form->display('updated_at');
        });
    }

}
